# 应用名称
#spring.application.name=spingboot
## 数据库驱动：
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## 数据源名称
#spring.datasource.name=defaultDataSource
## 数据库连接地址
#spring.datasource.url=jdbc:mysql://localhost:3306/lhq_blue?serverTimezone=GMT%2b8
# 数据库用户名&密码：
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lhq_blue?serverTimezone=GMT%2b8
    username: root
    password: lhqroot2020@
# 应用服务 WEB 访问端口
server:
  port: 9090
mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
